packages:
  - packages/core
  - packages/mcx-component
  - packages/types
  - packages/client
  - packages/create-mbler
  - packages/vite-plugin-mcx
  - packages/eslint-plugin-mcx
allowBuilds:
  esbuild: true
  simple-git-hooks: true
