// AUTO-GENERATED from @minecraft/server@2.9.0-beta.1.26.30-preview.21 index.d.ts by
// scripts/generate-events.mjs (WorldAfterEvents / WorldBeforeEvents
// property names). Do not edit by hand; re-run the script to refresh.
//
// This is the FALLBACK list, used when a user project has no resolvable
// @minecraft/server. At lint time the plugin normally extracts the lists
// from the project's own @minecraft/server and caches them under
// node_modules/.tmp/eslint-plugin-mcx/ (see src/event-source.ts).
export const WORLD_AFTER_EVENTS: readonly string[] = [
  "blockContainerClosed",
  "blockContainerOpened",
  "blockExplode",
  "buttonPush",
  "chatSend",
  "dataDrivenEntityTrigger",
  "effectAdd",
  "entityContainerClosed",
  "entityContainerOpened",
  "entityDie",
  "entityHeal",
  "entityHealthChanged",
  "entityHitBlock",
  "entityHitEntity",
  "entityHurt",
  "entityItemDrop",
  "entityItemPickup",
  "entityLoad",
  "entityRemove",
  "entitySpawn",
  "entityUpgrade",
  "explosion",
  "gameRuleChange",
  "itemCompleteUse",
  "itemReleaseUse",
  "itemStartUse",
  "itemStartUseOn",
  "itemStopUse",
  "itemStopUseOn",
  "itemUse",
  "leverAction",
  "messageReceive",
  "packSettingChange",
  "pistonActivate",
  "playerBreakBlock",
  "playerButtonInput",
  "playerDimensionChange",
  "playerEmote",
  "playerGameModeChange",
  "playerHotbarSelectedSlotChange",
  "playerInputModeChange",
  "playerInputPermissionCategoryChange",
  "playerInteractWithBlock",
  "playerInteractWithEntity",
  "playerInventoryItemChange",
  "playerJoin",
  "playerLeave",
  "playerPlaceBlock",
  "playerSpawn",
  "playerSwingStart",
  "playerUseNameTag",
  "pressurePlatePop",
  "pressurePlatePush",
  "projectileHitBlock",
  "projectileHitEntity",
  "targetBlockHit",
  "tripWireTrip",
  "weatherChange",
  "worldLoad"
];

export const WORLD_BEFORE_EVENTS: readonly string[] = [
  "chatSend",
  "effectAdd",
  "entityHeal",
  "entityHurt",
  "entityItemPickup",
  "entityRemove",
  "explosion",
  "itemUse",
  "playerBreakBlock",
  "playerGameModeChange",
  "playerInteractWithBlock",
  "playerInteractWithEntity",
  "playerLeave",
  "playerPlaceBlock",
  "weatherChange"
];
